eureka:
  client:
    service-url:
      # MUDANÃ‡A CRUCIAL AQUI ðŸ‘‡
      # Trocamos 'localhost' pelo nome do container 'eureka-server'
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Isso aqui Ã© o "auto-map": ele cria rotas automÃ¡ticas baseadas no nome do serviÃ§o no Eureka
      routes:
        - id: micro-vini-rota
          uri: lb://MICRO-SERVICO-VINI # "lb" de Load Balancer + nome do serviÃ§o no Eureka
          predicates:
            - Path=/vini/** # Tudo que chegar em localhost:8080/vini/ vai pro microserviÃ§o