eureka:
  client:
    service-url:
      # MUDANÃ‡A CRUCIAL AQUI ðŸ‘‡
      # Trocamos 'localhost' pelo nome do container 'eureka-server'
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true